modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Player%20Tracking"
logoFile="icon.png"

[[mods]]
modId="playertracking"
version="3.6"
displayName="Player Tracking"
displayURL="https://serilum.com/mod/player-tracking"
authors="Rick South"
description='''A PvP mod which allows tracking players via trackers in the world, originally created by mcpvp.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, aternosorg, Cherriesaurus, Linda Jansen, Michelle Smith, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.playertracking]]
    modId="collective"
    mandatory=true
    versionRange="[8.25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playertracking]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11]"
    ordering="NONE"
    side="BOTH"
